spring.application.name=incidentes
server.port= 8091
spring.datasource.url=jdbc:postgresql://ep-restless-band-apx3eegl-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0tmgie1XnRlu
spring.datasource.driver-class-name=org.postgresql.Driver



# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Creación automática de tablas (Corregido 'hibernate')
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
